default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: good_weekly_development

production:
  <<: *default
  database: good_weekly_production

test:
  <<: *default
  database: good_weekly_test
